// Static fallback data when database is not available
// Used for development/preview without running the database

import type { Locale } from '@/i18n/config'

const PROFESSIONAL_SUMMARY = {
  en: {
    headline: 'Senior Staff Engineer | CTO | Full-Stack Architect',
    tagline: 'If you need to build it, I can deliver it.',
    bio: `10+ years architecting and delivering production systems across the full stack. From migrating multi-million transaction apps to building complete SaaS platforms from scratch. I've helped build Truth Social in its early stages, created enterprise insurance platforms processing thousands of policies daily, and shipped a Google Marketplace-approved audit system. Currently Senior Staff Engineer at DBA and CTO of two startups. I specialize in turning complex requirements into working software.`,
    highlights: [
      'Enterprise Elixir/Phoenix systems at scale',
      'Full-stack from infrastructure to frontend',
      'Complex data migrations and refactoring',
      'Shopify, Stripe, and API integrations',
      'Kubernetes and cloud architecture',
    ],
  },
  es: {
    headline: 'Ingeniero Staff Senior | CTO | Arquitecto Full-Stack',
    tagline: 'Si necesitas construirlo, puedo entregarlo.',
    bio: `Mas de 10 anos arquitecturando y entregando sistemas de produccion en todo el stack. Desde migrar aplicaciones de millones de transacciones hasta construir plataformas SaaS completas desde cero. Ayude a construir Truth Social en sus primeras etapas, cree plataformas de seguros empresariales que procesan miles de polizas diariamente, y lance un sistema de auditoria aprobado en Google Marketplace. Actualmente Ingeniero Staff Senior en DBA y CTO de dos startups. Me especializo en convertir requisitos complejos en software funcional.`,
    highlights: [
      'Sistemas empresariales Elixir/Phoenix a escala',
      'Full-stack desde infraestructura hasta frontend',
      'Migraciones de datos complejas y refactorizacion',
      'Integraciones con Shopify, Stripe y APIs',
      'Kubernetes y arquitectura en la nube',
    ],
  },
  it: {
    headline: 'Staff Engineer Senior | CTO | Architetto Full-Stack',
    tagline: 'Se hai bisogno di costruirlo, posso realizzarlo.',
    bio: `Oltre 10 anni di esperienza nella progettazione e consegna di sistemi in produzione su tutto lo stack. Dalla migrazione di applicazioni con milioni di transazioni alla costruzione di piattaforme SaaS complete da zero. Ho contribuito a costruire Truth Social nelle sue prime fasi, creato piattaforme assicurative aziendali che elaborano migliaia di polizze al giorno, e lanciato un sistema di audit approvato su Google Marketplace. Attualmente Staff Engineer Senior presso DBA e CTO di due startup. Mi specializzo nel trasformare requisiti complessi in software funzionante.`,
    highlights: [
      'Sistemi aziendali Elixir/Phoenix su larga scala',
      'Full-stack dalla infrastruttura al frontend',
      'Migrazioni di dati complesse e refactoring',
      'Integrazioni con Shopify, Stripe e API',
      'Kubernetes e architettura cloud',
    ],
  },
}

const CURRENT_ROLES = {
  en: [
    {
      id: 'dba',
      slug: 'dba',
      title: 'Senior Staff Engineer',
      company: 'DBA',
      type: 'employment',
      description: 'Enterprise software development for insurance and financial services.',
    },
    {
      id: 'pmx',
      slug: 'pmx',
      title: 'CTO',
      company: 'PMX',
      type: 'leadership',
      description: 'Leading technical strategy for affiliate marketplace platform.',
    },
    {
      id: 'grctechme',
      slug: 'grctechme',
      title: 'CTO',
      company: 'GRCTechMe',
      type: 'leadership',
      description: 'Building audit and compliance technology for legal professionals.',
    },
  ],
  es: [
    {
      id: 'dba',
      slug: 'dba',
      title: 'Ingeniero Staff Senior',
      company: 'DBA',
      type: 'employment',
      description: 'Desarrollo de software empresarial para seguros y servicios financieros.',
    },
    {
      id: 'pmx',
      slug: 'pmx',
      title: 'CTO',
      company: 'PMX',
      type: 'leadership',
      description: 'Liderando la estrategia tecnica para plataforma de marketplace de afiliados.',
    },
    {
      id: 'grctechme',
      slug: 'grctechme',
      title: 'CTO',
      company: 'GRCTechMe',
      type: 'leadership',
      description: 'Construyendo tecnologia de auditoria y cumplimiento para profesionales legales.',
    },
  ],
  it: [
    {
      id: 'dba',
      slug: 'dba',
      title: 'Staff Engineer Senior',
      company: 'DBA',
      type: 'employment',
      description: 'Sviluppo software aziendale per assicurazioni e servizi finanziari.',
    },
    {
      id: 'pmx',
      slug: 'pmx',
      title: 'CTO',
      company: 'PMX',
      type: 'leadership',
      description: 'Guida della strategia tecnica per piattaforma marketplace affiliati.',
    },
    {
      id: 'grctechme',
      slug: 'grctechme',
      title: 'CTO',
      company: 'GRCTechMe',
      type: 'leadership',
      description: 'Costruzione di tecnologie di audit e compliance per professionisti legali.',
    },
  ],
}

const COMPANIES = [
  {
    id: 'dba',
    slug: 'dba',
    name: 'DBA Consulting',
    tagline: 'Enterprise Software Solutions',
    description: 'Custom software development, system architecture, and technical consulting.',
    url: 'https://dbadbadba.com/',
    services: ['Custom Software Development', 'System Architecture', 'Technical Consulting', 'Cloud Infrastructure'],
    icon: '🏢',
  },
  {
    id: 'pmx',
    slug: 'pmx',
    name: 'PMX',
    tagline: 'Affiliate Marketplace for E-commerce',
    description: 'Full marketing affiliates platform with payment system and Shopify integration.',
    url: 'https://getpmx.com',
    services: ['Shopify Integration', 'Affiliate Management', 'Payment Processing', 'Analytics Dashboard'],
    icon: '🛒',
  },
  {
    id: 'grctechme',
    slug: 'grctechme',
    name: 'GRCTechMe',
    tagline: 'Audit & Compliance Technology',
    description: 'Digital audit platform for lawyers and agencies. Google Marketplace approved.',
    url: 'https://grctechme.com/',
    services: ['Digital Audits', 'Compliance Management', 'Google Workspace Integration', 'Automated Reporting'],
    icon: '📋',
  },
]

const FEATURED_PROJECTS = {
  en: [
    {
      id: 'pearson-channels',
      slug: 'pearson-channels',
      name: 'Pearson Channels',
      tagline: 'B2B educational platform acquired by Pearson',
      description: 'Built the complete B2B product at ClutchPrep: full class app with grading, customizable content, and analytics.',
      impact: 'Product acquired by Pearson; now powers pearson.com/channels',
      techStack: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
      status: 'completed',
      links: { site: 'https://www.pearson.com/channels' },
    },
    {
      id: 'agencyrocket',
      slug: 'agencyrocket',
      name: 'AgencyRocket',
      tagline: 'Enterprise insurance back-office platform',
      description: 'Full-stack enterprise platform for insurance agencies. Multi-tenant architecture, real-time policy tracking.',
      impact: 'Processing thousands of policies daily across multiple carriers',
      techStack: ['Elixir', 'Phoenix', 'GraphQL', 'Vue.js', 'Kubernetes'],
      status: 'active',
      links: null,
    },
    {
      id: 'securecard-migration',
      slug: 'securecard-migration',
      name: 'SecureCard Migration',
      tagline: 'Multi-million transaction app migration',
      description: 'Migrated all queries from Node.js to Elixir on a banking card platform.',
      impact: 'Zero-downtime migration of mission-critical financial system',
      techStack: ['Elixir', 'Node.js', 'PostgreSQL'],
      status: 'completed',
      links: null,
    },
    {
      id: 'pmx-platform',
      slug: 'pmx-platform',
      name: 'PMX Platform',
      tagline: 'Full affiliate marketing marketplace',
      description: 'Built complete affiliate marketplace with Shopify full integration, payment system, and analytics.',
      impact: 'Live platform with active merchants and affiliates',
      techStack: ['Rails', 'Shopify API', 'Stripe', 'Next.js'],
      status: 'active',
      links: { site: 'https://getpmx.com' },
    },
    {
      id: 'auditechme',
      slug: 'auditechme',
      name: 'AuditechMe / GRCTechMe',
      tagline: 'Google Marketplace approved audit system',
      description: 'Built audit platform for lawyers and agencies. Google Workspace integration, multi-role system.',
      impact: 'Live on Google Marketplace with active users',
      techStack: ['React', 'Firebase', 'Google AI', 'Google Workspace API'],
      status: 'active',
      links: { site: 'https://grctechme.com/' },
    },
    {
      id: 'nebulith',
      slug: 'nebulith',
      name: 'Nebulith Engine',
      tagline: 'Open-source ASCII isometric game engine',
      description: 'Custom game engine for creating isometric worlds using ASCII art.',
      impact: null,
      techStack: ['TypeScript', 'Canvas API', 'Next.js', 'WebGL'],
      status: 'active',
      links: { demo: '/personal-projects/game-engine' },
    },
  ],
  es: [
    {
      id: 'pearson-channels',
      slug: 'pearson-channels',
      name: 'Pearson Channels',
      tagline: 'Plataforma educativa B2B adquirida por Pearson',
      description: 'Construi el producto B2B completo en ClutchPrep: aplicacion de clases con calificaciones y analiticas.',
      impact: 'Producto adquirido por Pearson; ahora alimenta pearson.com/channels',
      techStack: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
      status: 'completed',
      links: { site: 'https://www.pearson.com/channels' },
    },
    {
      id: 'agencyrocket',
      slug: 'agencyrocket',
      name: 'AgencyRocket',
      tagline: 'Plataforma de back-office empresarial para seguros',
      description: 'Plataforma empresarial full-stack para agencias de seguros. Arquitectura multi-inquilino.',
      impact: 'Procesando miles de polizas diariamente a traves de multiples aseguradoras',
      techStack: ['Elixir', 'Phoenix', 'GraphQL', 'Vue.js', 'Kubernetes'],
      status: 'active',
      links: null,
    },
    {
      id: 'securecard-migration',
      slug: 'securecard-migration',
      name: 'SecureCard Migration',
      tagline: 'Migracion de app con millones de transacciones',
      description: 'Migre todas las consultas de Node.js a Elixir en plataforma de tarjetas bancarias.',
      impact: 'Migracion sin tiempo de inactividad de sistema financiero critico',
      techStack: ['Elixir', 'Node.js', 'PostgreSQL'],
      status: 'completed',
      links: null,
    },
    {
      id: 'pmx-platform',
      slug: 'pmx-platform',
      name: 'PMX Platform',
      tagline: 'Marketplace completo de marketing de afiliados',
      description: 'Construi marketplace de afiliados completo con integracion Shopify y sistema de pagos.',
      impact: 'Plataforma en vivo con comerciantes y afiliados activos',
      techStack: ['Rails', 'Shopify API', 'Stripe', 'Next.js'],
      status: 'active',
      links: { site: 'https://getpmx.com' },
    },
    {
      id: 'auditechme',
      slug: 'auditechme',
      name: 'AuditechMe / GRCTechMe',
      tagline: 'Sistema de auditoria aprobado por Google Marketplace',
      description: 'Construi plataforma de auditoria para abogados y agencias con integracion Google Workspace.',
      impact: 'En vivo en Google Marketplace con usuarios activos',
      techStack: ['React', 'Firebase', 'Google AI', 'Google Workspace API'],
      status: 'active',
      links: { site: 'https://grctechme.com/' },
    },
    {
      id: 'nebulith',
      slug: 'nebulith',
      name: 'Nebulith Engine',
      tagline: 'Motor de juego isometrico ASCII de codigo abierto',
      description: 'Motor de juego personalizado para crear mundos isometricos usando arte ASCII.',
      impact: null,
      techStack: ['TypeScript', 'Canvas API', 'Next.js', 'WebGL'],
      status: 'active',
      links: { demo: '/personal-projects/game-engine' },
    },
  ],
  it: [
    {
      id: 'pearson-channels',
      slug: 'pearson-channels',
      name: 'Pearson Channels',
      tagline: 'Piattaforma educativa B2B acquisita da Pearson',
      description: 'Ho costruito il prodotto B2B completo in ClutchPrep: app completa per classi con valutazioni.',
      impact: 'Prodotto acquisito da Pearson; ora alimenta pearson.com/channels',
      techStack: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
      status: 'completed',
      links: { site: 'https://www.pearson.com/channels' },
    },
    {
      id: 'agencyrocket',
      slug: 'agencyrocket',
      name: 'AgencyRocket',
      tagline: 'Piattaforma back-office aziendale per assicurazioni',
      description: 'Piattaforma aziendale full-stack per agenzie assicurative. Architettura multi-tenant.',
      impact: 'Elaborando migliaia di polizze giornalmente attraverso piu assicuratori',
      techStack: ['Elixir', 'Phoenix', 'GraphQL', 'Vue.js', 'Kubernetes'],
      status: 'active',
      links: null,
    },
    {
      id: 'securecard-migration',
      slug: 'securecard-migration',
      name: 'SecureCard Migration',
      tagline: 'Migrazione app con milioni di transazioni',
      description: 'Ho migrato tutte le query da Node.js a Elixir su piattaforma di carte bancarie.',
      impact: 'Migrazione zero-downtime di sistema finanziario mission-critical',
      techStack: ['Elixir', 'Node.js', 'PostgreSQL'],
      status: 'completed',
      links: null,
    },
    {
      id: 'pmx-platform',
      slug: 'pmx-platform',
      name: 'PMX Platform',
      tagline: 'Marketplace completo di affiliate marketing',
      description: 'Ho costruito marketplace affiliati completo con integrazione Shopify e sistema di pagamento.',
      impact: 'Piattaforma live con merchant e affiliati attivi',
      techStack: ['Rails', 'Shopify API', 'Stripe', 'Next.js'],
      status: 'active',
      links: { site: 'https://getpmx.com' },
    },
    {
      id: 'auditechme',
      slug: 'auditechme',
      name: 'AuditechMe / GRCTechMe',
      tagline: 'Sistema di audit approvato su Google Marketplace',
      description: 'Ho costruito piattaforma di audit per avvocati e agenzie con integrazione Google Workspace.',
      impact: 'Live su Google Marketplace con utenti attivi',
      techStack: ['React', 'Firebase', 'Google AI', 'Google Workspace API'],
      status: 'active',
      links: { site: 'https://grctechme.com/' },
    },
    {
      id: 'nebulith',
      slug: 'nebulith',
      name: 'Nebulith Engine',
      tagline: 'Motore di gioco isometrico ASCII open-source',
      description: 'Motore di gioco personalizzato per creare mondi isometrici usando arte ASCII.',
      impact: null,
      techStack: ['TypeScript', 'Canvas API', 'Next.js', 'WebGL'],
      status: 'active',
      links: { demo: '/personal-projects/game-engine' },
    },
  ],
}

const TECH_STACK = {
  en: [
    { id: '1', name: 'Languages', icon: '💻', items: ['Elixir', 'TypeScript', 'JavaScript', 'Ruby', 'Python', 'C#', 'C++', 'PHP', 'SQL', 'HTML/CSS', 'Terraform/HCL'] },
    { id: '2', name: 'Backend Frameworks', icon: '⚙️', items: ['Phoenix', 'Rails', 'Express', 'Laravel', '.NET', 'Node.js', 'Ash Framework', 'Absinthe (GraphQL)'] },
    { id: '3', name: 'Frontend Frameworks', icon: '🎨', items: ['React', 'Vue.js', 'Angular', 'Next.js', 'Quasar', 'LiveView', 'Tailwind CSS', 'Three.js/WebGL'] },
    { id: '4', name: 'Databases', icon: '🗄️', items: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Elasticsearch', 'Firebase/Firestore'] },
    { id: '5', name: 'Cloud & DevOps', icon: '☁️', items: ['Docker', 'Kubernetes', 'Terraform', 'Google Cloud (GCP)', 'AWS', 'Azure (AKS)', 'Railway', 'Netlify', 'GitLab CI/CD', 'ArgoCD', 'GitHub Actions'] },
    { id: '6', name: 'Integrations & APIs', icon: '🔌', items: ['Shopify API', 'Stripe', 'Google Workspace API', 'Slack API', 'GraphQL/Apollo', 'REST APIs', 'OAuth/Auth0', 'Sentry'] },
    { id: '7', name: 'AI & Automation', icon: '🤖', items: ['Claude/Anthropic API', 'OpenAI/GPT', 'Google Gemini', 'Prompt Engineering', 'AI-assisted Development'] },
  ],
  es: [
    { id: '1', name: 'Lenguajes', icon: '💻', items: ['Elixir', 'TypeScript', 'JavaScript', 'Ruby', 'Python', 'C#', 'C++', 'PHP', 'SQL', 'HTML/CSS', 'Terraform/HCL'] },
    { id: '2', name: 'Frameworks Backend', icon: '⚙️', items: ['Phoenix', 'Rails', 'Express', 'Laravel', '.NET', 'Node.js', 'Ash Framework', 'Absinthe (GraphQL)'] },
    { id: '3', name: 'Frameworks Frontend', icon: '🎨', items: ['React', 'Vue.js', 'Angular', 'Next.js', 'Quasar', 'LiveView', 'Tailwind CSS', 'Three.js/WebGL'] },
    { id: '4', name: 'Bases de Datos', icon: '🗄️', items: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Elasticsearch', 'Firebase/Firestore'] },
    { id: '5', name: 'Nube y DevOps', icon: '☁️', items: ['Docker', 'Kubernetes', 'Terraform', 'Google Cloud (GCP)', 'AWS', 'Azure (AKS)', 'Railway', 'Netlify', 'GitLab CI/CD', 'ArgoCD', 'GitHub Actions'] },
    { id: '6', name: 'Integraciones y APIs', icon: '🔌', items: ['Shopify API', 'Stripe', 'Google Workspace API', 'Slack API', 'GraphQL/Apollo', 'REST APIs', 'OAuth/Auth0', 'Sentry'] },
    { id: '7', name: 'IA y Automatizacion', icon: '🤖', items: ['Claude/Anthropic API', 'OpenAI/GPT', 'Google Gemini', 'Prompt Engineering', 'AI-assisted Development'] },
  ],
  it: [
    { id: '1', name: 'Linguaggi', icon: '💻', items: ['Elixir', 'TypeScript', 'JavaScript', 'Ruby', 'Python', 'C#', 'C++', 'PHP', 'SQL', 'HTML/CSS', 'Terraform/HCL'] },
    { id: '2', name: 'Framework Backend', icon: '⚙️', items: ['Phoenix', 'Rails', 'Express', 'Laravel', '.NET', 'Node.js', 'Ash Framework', 'Absinthe (GraphQL)'] },
    { id: '3', name: 'Framework Frontend', icon: '🎨', items: ['React', 'Vue.js', 'Angular', 'Next.js', 'Quasar', 'LiveView', 'Tailwind CSS', 'Three.js/WebGL'] },
    { id: '4', name: 'Database', icon: '🗄️', items: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Elasticsearch', 'Firebase/Firestore'] },
    { id: '5', name: 'Cloud e DevOps', icon: '☁️', items: ['Docker', 'Kubernetes', 'Terraform', 'Google Cloud (GCP)', 'AWS', 'Azure (AKS)', 'Railway', 'Netlify', 'GitLab CI/CD', 'ArgoCD', 'GitHub Actions'] },
    { id: '6', name: 'Integrazioni e API', icon: '🔌', items: ['Shopify API', 'Stripe', 'Google Workspace API', 'Slack API', 'GraphQL/Apollo', 'REST APIs', 'OAuth/Auth0', 'Sentry'] },
    { id: '7', name: 'IA e Automazione', icon: '🤖', items: ['Claude/Anthropic API', 'OpenAI/GPT', 'Google Gemini', 'Prompt Engineering', 'AI-assisted Development'] },
  ],
}

const WORK_EXPERIENCE = {
  en: [
    {
      id: '1',
      title: 'Senior Staff Engineer',
      company: 'DBA Consulting',
      description: 'Leading enterprise software development for insurance and financial services.',
      startDate: new Date('2020-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Architected and delivered enterprise insurance platform processing thousands of policies daily',
        'Led large-scale user migration system for 50k+ users with zero-downtime deployment',
        'Built multi-tenant SaaS architecture with real-time policy tracking and carrier integration',
        'Implemented GraphQL APIs with Elixir/Phoenix and Vue.js frontends',
      ],
      skills: ['Elixir', 'Phoenix', 'Vue.js', 'Kubernetes', 'PostgreSQL', 'GraphQL'],
    },
    {
      id: '2',
      title: 'CTO & Co-Founder',
      company: 'PMX',
      description: 'Leading technical strategy for affiliate marketplace platform.',
      startDate: new Date('2022-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Built complete affiliate marketing marketplace with Shopify full integration',
        'Implemented payment processing with Stripe, commission tracking, and analytics',
        'Led product strategy and technical architecture decisions',
      ],
      skills: ['Rails', 'Next.js', 'Shopify API', 'Stripe', 'PostgreSQL'],
    },
    {
      id: '3',
      title: 'CTO & Co-Founder',
      company: 'GRCTechMe',
      description: 'Building audit and compliance technology for legal professionals.',
      startDate: new Date('2023-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Built audit platform approved for Google Marketplace',
        'Integrated Google Workspace API for seamless enterprise workflow',
        'Implemented AI-powered document analysis and compliance reporting',
      ],
      skills: ['React', 'Firebase', 'Google Workspace API', 'Google AI'],
    },
    {
      id: '4',
      title: 'Senior Software Engineer',
      company: 'ClutchPrep (acquired by Pearson)',
      description: 'Full-stack development for educational technology platform.',
      startDate: new Date('2018-01-01'),
      endDate: new Date('2020-01-01'),
      current: false,
      highlights: [
        'Built B2B educational platform that was acquired by Pearson',
        'Developed full class application with grading, customizable content, and analytics',
        'Product now powers pearson.com/channels',
      ],
      skills: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    },
    {
      id: '5',
      title: 'Software Engineer',
      company: 'SecureCard Financial',
      description: 'Backend development for financial services platform.',
      startDate: new Date('2016-01-01'),
      endDate: new Date('2018-01-01'),
      current: false,
      highlights: [
        'Migrated mission-critical banking application from Node.js to Elixir',
        'Zero-downtime migration of system handling millions of transactions',
        'Improved system performance and reliability',
      ],
      skills: ['Elixir', 'Node.js', 'PostgreSQL'],
    },
    {
      id: '6',
      title: 'Software Developer',
      company: 'Various Contracts & Projects',
      description: 'Full-stack development across various technologies.',
      startDate: new Date('2014-01-01'),
      endDate: new Date('2016-01-01'),
      current: false,
      highlights: [
        'Participated in early-stage development of Truth Social platform',
        'Built custom web applications for small businesses',
        'Full-stack development across Ruby, PHP, and JavaScript',
      ],
      skills: ['Ruby', 'PHP', 'JavaScript', 'MySQL'],
    },
  ],
  es: [
    {
      id: '1',
      title: 'Ingeniero Staff Senior',
      company: 'DBA Consulting',
      description: 'Liderando desarrollo de software empresarial para seguros y servicios financieros.',
      startDate: new Date('2020-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Arquitecte y entregue plataforma de seguros empresarial procesando miles de polizas diariamente',
        'Lidere sistema de migracion de usuarios a gran escala para 50k+ usuarios',
        'Construi arquitectura SaaS multi-inquilino con seguimiento de polizas en tiempo real',
        'Implemente APIs GraphQL con Elixir/Phoenix y frontends Vue.js',
      ],
      skills: ['Elixir', 'Phoenix', 'Vue.js', 'Kubernetes', 'PostgreSQL', 'GraphQL'],
    },
    {
      id: '2',
      title: 'CTO y Co-Fundador',
      company: 'PMX',
      description: 'Liderando estrategia tecnica para plataforma de marketplace de afiliados.',
      startDate: new Date('2022-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Construi marketplace completo de marketing de afiliados con integracion total con Shopify',
        'Implemente procesamiento de pagos con Stripe, seguimiento de comisiones y analiticas',
        'Lidere estrategia de producto y decisiones de arquitectura tecnica',
      ],
      skills: ['Rails', 'Next.js', 'Shopify API', 'Stripe', 'PostgreSQL'],
    },
    {
      id: '3',
      title: 'CTO y Co-Fundador',
      company: 'GRCTechMe',
      description: 'Construyendo tecnologia de auditoria y cumplimiento para profesionales legales.',
      startDate: new Date('2023-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Construi plataforma de auditoria aprobada para Google Marketplace',
        'Integre Google Workspace API para flujo de trabajo empresarial sin problemas',
        'Implemente analisis de documentos impulsado por IA y reportes de cumplimiento',
      ],
      skills: ['React', 'Firebase', 'Google Workspace API', 'Google AI'],
    },
    {
      id: '4',
      title: 'Ingeniero de Software Senior',
      company: 'ClutchPrep (adquirida por Pearson)',
      description: 'Desarrollo full-stack para plataforma de tecnologia educativa.',
      startDate: new Date('2018-01-01'),
      endDate: new Date('2020-01-01'),
      current: false,
      highlights: [
        'Construi plataforma educativa B2B que fue adquirida por Pearson',
        'Desarrolle aplicacion de clases completa con calificaciones y analiticas',
        'El producto ahora alimenta pearson.com/channels',
      ],
      skills: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    },
    {
      id: '5',
      title: 'Ingeniero de Software',
      company: 'SecureCard Financial',
      description: 'Desarrollo backend para plataforma de servicios financieros.',
      startDate: new Date('2016-01-01'),
      endDate: new Date('2018-01-01'),
      current: false,
      highlights: [
        'Migre aplicacion bancaria critica de Node.js a Elixir',
        'Migracion sin tiempo de inactividad de sistema que maneja millones de transacciones',
        'Mejore el rendimiento y confiabilidad del sistema',
      ],
      skills: ['Elixir', 'Node.js', 'PostgreSQL'],
    },
    {
      id: '6',
      title: 'Desarrollador de Software',
      company: 'Varios Contratos y Proyectos',
      description: 'Desarrollo full-stack a traves de varias tecnologias.',
      startDate: new Date('2014-01-01'),
      endDate: new Date('2016-01-01'),
      current: false,
      highlights: [
        'Participe en el desarrollo de etapa inicial de la plataforma Truth Social',
        'Construi aplicaciones web personalizadas para pequenas empresas',
        'Desarrollo full-stack en Ruby, PHP y JavaScript',
      ],
      skills: ['Ruby', 'PHP', 'JavaScript', 'MySQL'],
    },
  ],
  it: [
    {
      id: '1',
      title: 'Staff Engineer Senior',
      company: 'DBA Consulting',
      description: 'Guida dello sviluppo software aziendale per assicurazioni e servizi finanziari.',
      startDate: new Date('2020-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Ho progettato e consegnato una piattaforma assicurativa che elabora migliaia di polizze al giorno',
        'Ho guidato un sistema di migrazione utenti su larga scala per 50k+ utenti',
        'Ho costruito architettura SaaS multi-tenant con tracciamento polizze in tempo reale',
        'Ho implementato API GraphQL con Elixir/Phoenix e frontend Vue.js',
      ],
      skills: ['Elixir', 'Phoenix', 'Vue.js', 'Kubernetes', 'PostgreSQL', 'GraphQL'],
    },
    {
      id: '2',
      title: 'CTO e Co-Fondatore',
      company: 'PMX',
      description: 'Guida della strategia tecnica per piattaforma marketplace affiliati.',
      startDate: new Date('2022-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Ho costruito marketplace completo di affiliate marketing con integrazione Shopify totale',
        'Ho implementato elaborazione pagamenti con Stripe, tracciamento commissioni e analytics',
        'Ho guidato la strategia di prodotto e le decisioni di architettura tecnica',
      ],
      skills: ['Rails', 'Next.js', 'Shopify API', 'Stripe', 'PostgreSQL'],
    },
    {
      id: '3',
      title: 'CTO e Co-Fondatore',
      company: 'GRCTechMe',
      description: 'Costruzione di tecnologie di audit e compliance per professionisti legali.',
      startDate: new Date('2023-01-01'),
      endDate: null,
      current: true,
      highlights: [
        'Ho costruito una piattaforma di audit approvata per Google Marketplace',
        'Ho integrato Google Workspace API per un workflow aziendale senza problemi',
        'Ho implementato analisi documenti alimentata da IA e reportistica compliance',
      ],
      skills: ['React', 'Firebase', 'Google Workspace API', 'Google AI'],
    },
    {
      id: '4',
      title: 'Ingegnere Software Senior',
      company: 'ClutchPrep (acquisita da Pearson)',
      description: 'Sviluppo full-stack per piattaforma di tecnologia educativa.',
      startDate: new Date('2018-01-01'),
      endDate: new Date('2020-01-01'),
      current: false,
      highlights: [
        'Ho costruito una piattaforma educativa B2B acquisita da Pearson',
        'Ho sviluppato applicazione completa per classi con valutazioni e analytics',
        'Il prodotto ora alimenta pearson.com/channels',
      ],
      skills: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    },
    {
      id: '5',
      title: 'Ingegnere Software',
      company: 'SecureCard Financial',
      description: 'Sviluppo backend per piattaforma di servizi finanziari.',
      startDate: new Date('2016-01-01'),
      endDate: new Date('2018-01-01'),
      current: false,
      highlights: [
        'Ho migrato applicazione bancaria mission-critical da Node.js a Elixir',
        'Migrazione zero-downtime di sistema che gestisce milioni di transazioni',
        'Ho migliorato le prestazioni e affidabilita del sistema',
      ],
      skills: ['Elixir', 'Node.js', 'PostgreSQL'],
    },
    {
      id: '6',
      title: 'Sviluppatore Software',
      company: 'Vari Contratti e Progetti',
      description: 'Sviluppo full-stack attraverso varie tecnologie.',
      startDate: new Date('2014-01-01'),
      endDate: new Date('2016-01-01'),
      current: false,
      highlights: [
        'Ho partecipato allo sviluppo iniziale della piattaforma Truth Social',
        'Ho costruito applicazioni web personalizzate per piccole imprese',
        'Sviluppo full-stack in Ruby, PHP e JavaScript',
      ],
      skills: ['Ruby', 'PHP', 'JavaScript', 'MySQL'],
    },
  ],
}

export async function getStaticCVData(locale: Locale) {
  return {
    professionalSummary: PROFESSIONAL_SUMMARY[locale],
    currentRoles: CURRENT_ROLES[locale],
    companies: COMPANIES,
    featuredProjects: FEATURED_PROJECTS[locale],
    techStack: TECH_STACK[locale],
    workExperience: WORK_EXPERIENCE[locale],
  }
}
