'use client'

import { useTheme } from '@/themes/ThemeContext'
import { useWorldTransition } from '@/themes/WorldTransitionContext'
import { getThemeById } from '@/themes/themes'
import type { World } from '@/themes/worlds'

interface WorldCardProps {
  world: World
  /** The world currently being viewed — shown highlighted and not clickable. */
  isCurrent?: boolean
}

/**
 * A single tile in the Worlds grid. The card FRAME is styled to the *current* theme
 * (so the section feels native), while the preview shows a lightweight static hero
 * screenshot of the *destination* world. Clicking fires the portal transition.
 *
 * We use a pre-rendered webp (public/world-previews/<id>.webp, generated by
 * scripts/capture-world-previews.sh) instead of mounting the real themed layout — 16
 * live components dragged the page to a crawl. Regenerate the webps after changing a
 * theme's hero.
 */
export default function WorldCard({ world, isCurrent = false }: WorldCardProps) {
  const { theme: currentTheme } = useTheme() // hosting theme -> card frame chrome
  const { selectWorld } = useWorldTransition()
  const destTheme = getThemeById(world.id) // destination world -> name + accent hint

  return (
    <button
      type="button"
      onClick={() => { if (!isCurrent) selectWorld(world.id) }}
      aria-current={isCurrent ? 'true' : undefined}
      className={`wc-card group relative flex flex-col overflow-hidden rounded-lg text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 ${isCurrent ? 'cursor-default' : ''}`}
      style={{
        backgroundColor: currentTheme.colors.surface,
        border: `2px solid ${isCurrent ? currentTheme.colors.accent : currentTheme.colors.border}`,
        outlineColor: currentTheme.colors.accent,
        boxShadow: isCurrent ? `0 0 0 1px ${currentTheme.colors.accent}, 0 0 22px ${currentTheme.colors.accent}55` : undefined,
      }}
      aria-label={isCurrent ? `${destTheme.name} — current world` : `Enter ${destTheme.name} — ${destTheme.description}`}
    >
      {/* Static hero preview of the destination world (decorative, lazy-loaded) */}
      <div
        className="wc-frame relative w-full overflow-hidden"
        style={{ aspectRatio: '16 / 10', backgroundColor: destTheme.colors.background }}
        aria-hidden="true"
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={`/world-previews/${world.id}.webp`}
          alt=""
          loading="lazy"
          decoding="async"
          className="absolute inset-0 h-full w-full object-cover object-top"
        />
        {/* Glass scrim so the preview reads as a "screen" and the hover sheen lands */}
        <div className="wc-scrim pointer-events-none absolute inset-0" aria-hidden="true" />
      </div>

      {/* Label plate — styled to the current theme, with a destination-accent hint */}
      <div
        className="relative z-10 flex items-center justify-between gap-3 px-4 py-3"
        style={{ borderTop: `1px solid ${currentTheme.colors.border}` }}
      >
        <div className="flex min-w-0 items-center gap-2">
          <span
            className="h-2.5 w-2.5 shrink-0 rounded-full"
            style={{ backgroundColor: destTheme.colors.accent }}
            aria-hidden="true"
          />
          <div className="min-w-0">
            <div
              className="truncate text-sm font-bold tracking-wide"
              style={{ color: currentTheme.colors.text }}
            >
              {destTheme.name}
            </div>
            <div
              className="truncate text-xs"
              style={{ color: currentTheme.colors.textMuted }}
            >
              {destTheme.description}
            </div>
          </div>
        </div>
        <span
          className="shrink-0 rounded px-2 py-1 text-[10px] uppercase tracking-wider"
          style={{
            color: isCurrent ? currentTheme.colors.background : currentTheme.colors.accent,
            backgroundColor: isCurrent ? currentTheme.colors.accent : undefined,
            border: `1px solid ${isCurrent ? currentTheme.colors.accent : currentTheme.colors.border}`,
          }}
        >
          {isCurrent ? '✓ Current' : world.category}
        </span>
      </div>
    </button>
  )
}
